name: friday
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_1.jpeg
    - images/
  fonts:
    - family: Black Ops One
      fonts:
        - asset: fonts/BlackOpsOne-Regular.ttf
    - family: Silkscreen
      fonts:
        - asset: fonts/Silkscreen-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo_2.png"
  remove_alpha_ios: true
